# Generated by Django 4.1.7 on 2023-10-29 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='phone_no',
            new_name='phone',
        ),
    ]
